const ActionType={
    CHANGEUSERNAME:"CHANGEUSERNAME",
    ADDACCOUNT:"ADDACCOUNT",
    ADDITEM:"ADDITEM",
    LOADITEM:"LOADITEM",
    LOADVENDER:"LOADVENDER",
    ADDVENDER:"ADDVENDER",
    LOADCUSTOMER:"LOADCUSTOMER",
    ADDCUSTOMER:"ADDCUSTOMER",
    LOADPURCHASE:"LOADPURCHASE",
    LOADACCOUNT:"LOADACCOUNT"

}
export default ActionType;